# Generated by Django 5.0.1 on 2024-02-20 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_paid_course_alter_payment_paid_lesson_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
