# Generated by Django 5.0.1 on 2024-02-06 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='course_previews/', verbose_name='картинка')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='lesson_previews/', verbose_name='картинка')),
                ('description', models.TextField(verbose_name='описание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='видеоурок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='курс', to='lms.course')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
                'ordering': ['course', 'name'],
            },
        ),
    ]
