# Generated by Django 5.0.1 on 2024-02-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_lms_course_name_be59f6_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='lms_course_name_be59f6_idx',
        ),
    ]
